### ISSUE TITLE
Lack of the QA experiment

### ISSUE THREAD

**Issue by susht3** [danoyu/AS_project-Skim-RNN#1]
I have two questions about this work:

1. The paper applys skim-rnn on classification tasks and question answering tasks, and this project only runs classification task，will you add QA task in future ? 

2. The paper uses gumbel softmax instead of sampling, have you make comparison with RL methods？The action number here is just two, i think RL can work it.

Thanks

**Comment by danoyu** [comment]
Hi,

1.  I won't add QA task in the future

2. I made no comparison




On Feb 27, 2018 09:47, "Shuting Su" <notifications@github.com> wrote:

I have two questions about this work:

   1.

   The paper applys skim-rnn on classification tasks and question answering
   tasks, and this project only runs classification task，will you add QA task
   in future ?
   2.

   The paper uses gumbel softmax instead of sampling, have you make
   comparison with RL methods？The action number here is just two, i think RL
   can work it.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/danoyu/AS_project-Skim-RNN/issues/1>, or mute the thread
